### ISSUE TITLE
net-im/swift depends on non-existing x11-libs/qt-webkit

### ISSUE THREAD

**Issue by hartwork** [posativ/overlay#4]
```
# sudo emerge net-im/swift
[..]
emerge: there are no ebuilds to satisfy "x11-libs/qt-webkit".
(dependency required by "net-im/swift-2.0::posativ[qt4]" [ebuild])
(dependency required by "net-im/swift" [argument])
```

**Comment by posativ** [comment]
Oh, never built with `qt` support.

**Comment by hartwork** [comment]
Is there a chance for a fix?

For Qt Webkit dev-qt/qtwebkit slot 4 or 5 it seems to be.

**Comment by posativ** [comment]
I'll check later (in one or two weeks, currently very limited internet connection :/)

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
